/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.dawan.gui;

import fr.dawan.domain.Formateur;
import fr.dawan.domain.Formation;
import fr.dawan.domain.Lieu;
import fr.dawan.domain.Session;

/**
 *
 * @author bmarron
 */
public class SessionDetails extends javax.swing.JPanel {

    private Session sessionCourante;

    /**
     * Creates new form SessionDetails
     */
    public SessionDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titreLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lieuLbl = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dateDebutLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dureeLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nbPlacesLbl = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nbInscritsLbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        prixHTLbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        montantTotalLbl = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        formateurLbl = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Détails"));
        setLayout(new java.awt.GridLayout(0, 4));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel1.setText("Titre");
        add(jLabel1);

        titreLbl.setText("jLabel2");
        add(titreLbl);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel4.setText("Lieu");
        add(jLabel4);

        lieuLbl.setText("jLabel6");
        add(lieuLbl);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel13.setText("Date de début");
        add(jLabel13);

        dateDebutLbl.setText("jLabel5");
        add(dateDebutLbl);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel3.setText("Durée");
        add(jLabel3);

        dureeLbl.setText("jLabel10");
        add(dureeLbl);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel7.setText("Nb places");
        add(jLabel7);

        nbPlacesLbl.setText("jLabel12");
        add(nbPlacesLbl);

        jLabel14.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel14.setText("Inscrits");
        add(jLabel14);

        nbInscritsLbl.setText("jLabel8");
        add(nbInscritsLbl);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel9.setText("Prix HT");
        add(jLabel9);

        prixHTLbl.setText("jLabel17");
        add(prixHTLbl);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel11.setText("Montant total");
        add(jLabel11);

        montantTotalLbl.setText("jLabel19");
        add(montantTotalLbl);

        jLabel15.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel15.setText("Formateur");
        add(jLabel15);

        formateurLbl.setText("jLabel16");
        add(formateurLbl);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateDebutLbl;
    private javax.swing.JLabel dureeLbl;
    private javax.swing.JLabel formateurLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lieuLbl;
    private javax.swing.JLabel montantTotalLbl;
    private javax.swing.JLabel nbInscritsLbl;
    private javax.swing.JLabel nbPlacesLbl;
    private javax.swing.JLabel prixHTLbl;
    private javax.swing.JLabel titreLbl;
    // End of variables declaration//GEN-END:variables

    void setSessionCourante(Session sess1) {
        sessionCourante = sess1;
        dateDebutLbl.setText(sess1.getDateDebut().toString());
        nbInscritsLbl.setText(String.valueOf(sess1.getNbInscrits()));
        montantTotalLbl.setText(String.valueOf(sess1.calculMontantTTC()));
        Formation f = sess1.getFormationDispensee();
        if (f != null) {
            titreLbl.setText(f.getTitre());
            prixHTLbl.setText(String.valueOf(f.getPrixHT()));
            dureeLbl.setText(String.valueOf(f.getDuree()));
        }
        Lieu l = sess1.getSalleDeFormation();
        if (l != null) {
            lieuLbl.setText(l.getLibelle());
            nbPlacesLbl.setText(String.valueOf(l.getNbPlaces()));
        }
        Formateur form = sess1.getFormateurAffecte();
        if (form != null) {
            formateurLbl.setText(form.getPrenom()+" "+form.getNom());
        } else {
            formateurLbl.setText("Non affectée");
        }
    }
}
